language: node_js
node_js:
- '8'
- '10'
- '12'
before_script:
- "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
- "chmod +x ./cc-test-reporter"
- "./cc-test-reporter before-build"
# deploy:
#   provider: npm
#   # TODO: Connect for travis?
#   email: devops@bowtie.co
#   on:
#     tags: true
#     repo: bowtie-co/node-simple-cli
#   api_key:
#     secure: xxx
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"